import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[font]
size = 8.0

[font.normal]
family = "Noto Sans Mono Medium"
style = "Normal"

[shell]
args = ["-c", "zsh"]
program = "/bin/zsh"

[window]
opacity = 0.9
